### ISSUE TITLE
node-gyp fails to install on VS 2017

### ISSUE THREAD

**Issue by reyx** [Vidyo/VidyoConnector-electron#3]
Hey guys,

I have followed all steps on windows 10 with visual studi 2017 with no success:

After command 
```
node-gyp rebuild --target=2.0.5 --arch=x64 --dist-url=https://atom.io/download/electron --msvs_version=2017
```
In the first attempt i receive the following output:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@8.11.2 | win32 | x64
gyp info spawn C:\Python27\python2.EXE
gyp info spawn args [ 'C:\\Users\\regis\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\projects\\electron\\samurai-electron\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\regis\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\regis\\.node-gyp\\iojs-2.0.5\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\regis\\.node-gyp\\iojs-2.0.5',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\regis\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\regis\\.node-gyp\\iojs-2.0.5\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\projects\\electron\\samurai-electron',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\projects\\electron\\samurai-electron\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
D:\projects\electron\samurai-electron\build\VidyoAddon.vcxproj(21,3): error MSB4019: The imported project "C:\Program F
iles (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Im
port> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\regis\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\regis\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.5" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--msvs_version=2017"
gyp ERR! cwd D:\projects\electron\samurai-electron
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
```

And thats OK because i dont have the file Microsoft.Cpp.Default.props on this folder so i checked and have this file in 2 different folders:
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets

On the node-gyp forum i found the environment variable that changes this location, so i've tried:

set VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140

With this output:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@8.11.2 | win32 | x64
gyp info spawn C:\Python27\python2.EXE
gyp info spawn args [ 'C:\\Users\\regis\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\projects\\electron\\samurai-electron\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\regis\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\regis\\.node-gyp\\iojs-2.0.5\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\regis\\.node-gyp\\iojs-2.0.5',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\regis\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\regis\\.node-gyp\\iojs-2.0.5\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\projects\\electron\\samurai-electron',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\projects\\electron\\samurai-electron\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build t
ools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 bui
ld tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-cli
ck the solution, and then selecting "Retarget solution". [D:\projects\electron\samurai-electron\build\VidyoAddon.vcxpro
j]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\regis\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\regis\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.5" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--msvs_version=2017"
gyp ERR! cwd D:\projects\electron\samurai-electron
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
```

And with the visual studio path:
set VCTargetsPath=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@8.11.2 | win32 | x64
gyp info spawn C:\Python27\python2.EXE
gyp info spawn args [ 'C:\\Users\\regis\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\projects\\electron\\samurai-electron\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\regis\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\regis\\.node-gyp\\iojs-2.0.5\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\regis\\.node-gyp\\iojs-2.0.5',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\regis\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\regis\\.node-gyp\\iojs-2.0.5\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\projects\\electron\\samurai-electron',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\projects\\electron\\samurai-electron\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.DesignTime.targets
(488,5): error MSB4062: The "SetEnv" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Visual
 Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Build.CppTasks.Common.dll. Could not load file or assembly 'M
icrosoft.Build.Utilities.Core, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its depend
encies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assemb
ly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Fr
amework.ITask. [D:\projects\electron\samurai-electron\build\VidyoAddon.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\regis\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\regis\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.5" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--msvs_version=2017"
gyp ERR! cwd D:\projects\electron\samurai-electron
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
```

Can you help me plz?

**Comment by LuckStock** [comment]
Have you found the solution? 
Fighting the same issue for several days already.

**Comment by fscamuzzi2** [comment]
Hi .. Same problem Here!!! .. any news??

**Comment by GoodnessEzeokafor** [comment]
Sorry bt were u able to fix this???

**Comment by slorelloVidyo** [comment]
This looks like it's likely an issue with node-gyp finding the correct version of VisualStudio:
This is the first few lines of output from my trial run
`X:\Projects\VidyoConnector-electron>node-gyp rebuild --target=2.0.4 --arch=x64 --dist-url=https://atom.io/download/electron -msvs_version=2017
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.2
gyp info using node@8.12.0 | win32 | x64
gyp info find Python using Python version 2.7.0 found at "C:\Python27\python.exe"
gyp info find VS using VS2017 (15.9.28307.222) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python27\python.exe`

notice how it differs from reyx's in that the steps for find VS actually executed.  As a matter of fact, in spite of the fact that he's using VS2017 it seems to be trying to aim him at VS 2015

Unfortunately I can't reproduce this in my environment but I found this article: https://spin.atomicobject.com/2019/03/27/node-gyp-windows/ which seems like it will be of a lot of help.

If you continue to have problems please feel free to contact us at the helpdesk support@vidyo.io
